/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol/thrift/comsumer_constants.h"

namespace essential { namespace consumer {

const comsumerConstants g_comsumer_constants;

comsumerConstants::comsumerConstants() {
}

}} // namespace

